// simple exception handling
package module1

/* func main() {
	fmt.Println("enter a +ve number ")
	var i int
	fmt.Scan(&i)

	defer func() {

		if r := recover(); r != nil {
			fmt.Println("recovered from panic ", r)
		}

	}()

	if i < 0 {

		panic("a -ve number ")

	}
} */
